# Generated by Django 3.1 on 2026-03-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20260318_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_superadmin',
        ),
    ]
